using PresentationWpf.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace PresentationWpf.Views
{
    /// <summary>
    /// Interaction logic for DataBaseView.xaml
    /// </summary>
    public partial class DataBaseView : UserControl
    {
        public DataBaseView()
        {
            InitializeComponent();
        }

        private void ScrollUp_Click(object sender, RoutedEventArgs e)
        {
            SidebarScroll.ScrollToVerticalOffset(SidebarScroll.VerticalOffset - 50);
        }

        private void ScrollDown_Click(object sender, RoutedEventArgs e)
        {
            SidebarScroll.ScrollToVerticalOffset(SidebarScroll.VerticalOffset + 50);
        }

        // Hide dummy row visually (before it displays)
        private void Grid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            var vm = DataContext as DataBaseViewModel;
            if (vm == null) return;

            if (vm.HasDummyRow && e.Row.GetIndex() == 0)
                e.Row.Visibility = Visibility.Collapsed;
        }

        // After columns generated → remove dummy row from ItemsSource
        private void Grid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            var vm = DataContext as DataBaseViewModel;
            if (vm == null || !vm.HasDummyRow) return;

            // Remove dummy row permanently
            if (vm.TableData.Count > 0)
            {
                vm.TableData.RemoveAt(0);
            }

            vm.HasDummyRow = false;
        }

        private void DataGrid_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            var grid = sender as DataGrid;

            // COPY ===============================
            if (e.Key == Key.C && Keyboard.Modifiers == ModifierKeys.Control)
            {
                CopySelectedCells(grid);
                e.Handled = true;
            }

            // PASTE ==============================
            if (e.Key == Key.V && Keyboard.Modifiers == ModifierKeys.Control)
            {
                PasteIntoGrid(grid);
                e.Handled = true;
            }
        }

        private void CopySelectedCells(DataGrid grid)
        {
            var selectedCells = grid.SelectedCells;
            if (!selectedCells.Any())
                return;

            // group cells by row
            var rows = selectedCells
                .GroupBy(c => c.Item)
                .Select(g =>
                    string.Join("\t",
                        g.OrderBy(c => grid.Columns.IndexOf(c.Column))
                         .Select(c =>
                         {
                             var pi = c.Column.SortMemberPath;
                             if (pi == null) return "";
                             var prop = c.Item.GetType().GetProperty(pi);
                             var val = prop?.GetValue(c.Item);
                             return val?.ToString() ?? "";
                         })
                    )
                );

            string output = string.Join("\n", rows);
            Clipboard.SetText(output);
        }
        private void PasteIntoGrid(DataGrid grid)
        {
            // Commit edits before paste
            if (!grid.CommitEdit(DataGridEditingUnit.Cell, true))
                grid.CancelEdit();
            if (!grid.CommitEdit(DataGridEditingUnit.Row, true))
                grid.CancelEdit();

            string clip = Clipboard.GetText();
            if (string.IsNullOrWhiteSpace(clip))
                return;

            var vm = grid.DataContext as DataBaseViewModel;
            if (vm == null)
                return;

            bool allowId = vm.SelectedTableName == "Customers"; // only Customers allows ID paste

            // Columns that can accept pasted data
            var pasteColumns = grid.Columns
                .Where(c => c.Visibility == Visibility.Visible)
                .Where(c => c is DataGridBoundColumn bc && !c.IsReadOnly)
                .Cast<DataGridBoundColumn>()
                .Select(col =>
                {
                    var binding = col.Binding as Binding;
                    return new
                    {
                        Column = col,
                        Property = binding?.Path?.Path
                    };
                })
                .Where(x =>
                    !string.IsNullOrWhiteSpace(x.Property) &&
                    (allowId || x.Property != "Id") // block ID paste for non-customer tables
                )
                .ToList();

            if (pasteColumns.Count == 0)
                return;

            int startRow = grid.Items.IndexOf(grid.CurrentItem);
            int startCol = pasteColumns.FindIndex(x => x.Column == grid.CurrentColumn);
            if (startCol < 0) startCol = 0;

            var lines = clip.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            for (int r = 0; r < lines.Length; r++)
            {
                string[] cells = lines[r].Split('\t');
                int rowIndex = startRow + r;

                object rowObj;

                if (rowIndex >= grid.Items.Count)
                    rowObj = vm.CreateNewRow();  // auto-add row
                else
                    rowObj = grid.Items[rowIndex];

                for (int c = 0; c < cells.Length; c++)
                {
                    int colIndex = startCol + c;
                    if (colIndex >= pasteColumns.Count)
                        break;

                    string propName = pasteColumns[colIndex].Property;
                    if (string.IsNullOrWhiteSpace(propName))
                        continue;

                    var propInfo = rowObj.GetType().GetProperty(propName);
                    if (propInfo == null || !propInfo.CanWrite)
                        continue;

                    // Clean text
                    string cleanedText = cells[c].Trim();

                    // SPECIAL HANDLING FOR ID FIELD
                    if (propName == "Id")
                    {
                        // Customer IDs are strings (always paste)
                        if (propInfo.PropertyType == typeof(string))
                        {
                            propInfo.SetValue(rowObj, cleanedText);
                            continue;
                        }

                        // Other tables use numeric identity:
                        // Excel "" OR "0" → treat as NEW row → Id = null
                        if (string.IsNullOrWhiteSpace(cleanedText) || cleanedText == "0")
                        {
                            propInfo.SetValue(rowObj, null);
                            continue;
                        }

                        // Excel contains something → convert normally
                        try
                        {
                            object idValue = Convert.ChangeType(cleanedText, propInfo.PropertyType);
                            propInfo.SetValue(rowObj, idValue);
                        }
                        catch { }

                        continue;
                    }

                    // Ordinary property conversion
                    try
                    {
                        object value = cleanedText;

                        if (propInfo.PropertyType != typeof(string))
                            value = Convert.ChangeType(cleanedText, propInfo.PropertyType);

                        propInfo.SetValue(rowObj, value);
                    }
                    catch
                    {
                        // ignore bad conversions
                    }
                }
            }

            grid.Items.Refresh();
        }

        private static string CleanCell(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return null;

            return input
                .Replace("\t", "")
                .Replace("\r", "")
                .Replace("\n", "")
                .Trim();
        }



    }
}
